### ISSUE TITLE
mask_rcnn_coco.h5请问下这个文件已经放在目录下了，但是还是报错

### ISSUE THREAD

**Issue by paything** [fb1502/Mask_RCNN_3D#1]
python3 3d_image.py -i images/persons.jpg -o images/persons_3d.jpg
Traceback (most recent call last):
  File "3d_image.py", line 11, in <module>
    from samples import coco
  File "/Users/paything/Downloads/Mask_RCNN_3D-master/samples/coco.py", line 42, in <module>
    from pycocotools.coco import COCO
ModuleNotFoundError: No module named 'pycocotools'

**Comment by paything** [comment]
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Read original image successfully! The original image shape is:
(800, 600, 3)
Change gray image successfully! The gray image shape is:
(800, 600)
2019-04-15 14:51:19.535608: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/usr/local/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
there are n_instances in this picture: 5

**Comment by fb1502** [comment]
可以升级tf试试。如果你有GPU，还是用GPU会比较块，针对CPU优化差别比较有限

**Comment by paything** [comment]
https://b23.tv/av46966128

作者可以考虑升级一下代码吗，处理的时候把上下的内容做一部分遮挡，效果应该好很多

遮挡线条颜色可选黑白色

**Comment by fb1502** [comment]
谢谢链接，打算升级下代码
